version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./edgetech-core/mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
  filesaver:
    image: iqtlabs/edgetech-filesaver:latest
    build:
      context: ./edgetech-filesaver/filesaver
      dockerfile: ./Dockerfile
    environment:
      - TO_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - C2C_TOPIC=/AISonobuoy/<HOSTNAME>/C2C/edgetech-c2c/string
      - DATA_ROOT=/sensor-data
      - SENSOR_DIR=ais
      - FILE_PREFIX=daisy_ais_
      - MQTT_IP=mqtt
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
  core:
    image: iqtlabs/edgetech-core:latest
    build:
      context: ./edgetech-core/core
      dockerfile: ./Dockerfile
    depends_on: 
      - mqtt
  daisy:
    image: iqtlabs/edgetech-daisy:latest
    devices:
      - "/dev/ttyACM0:/dev/serial0"
    environment:
      - SEND_DATA_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - SERIAL_PORT=/dev/serial0
      - MQTT_IP=mqtt
    build:
      context: ./edgetech-daisy/daisy
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on: 
      - mqtt
  c2:
    image: iqtlabs/edgetech-c2:latest
    build:
      context: ./edgetech-c2/c2
      dockerfile: ./Dockerfile
    environment:
      - NEXT_FILE_TOPIC=/AISonobuoy/<HOSTNAME>/C2/edgetech-c2/string
      - MQTT_IP=mqtt
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
  telemetry:
    image: iqtlabs/edgetech-telemetry:latest
    build:
      context: ./edgetech-telemetry-pinephone/telemetry
      dockerfile: ./Dockerfile
    environment:
      - TELEMETRY_TOPIC=/AISonobuoy/<HOSTNAME>/telemetry/telemetry/string
      - BATTERY_CAPACITY_FILE_PATH=/root/battery_capacity
      - UPTIME_FILE_PATH=/root/uptime
      - MQTT_IP=mqtt
    volumes:
      - /sys/class/power_supply/rk818-battery/capacity:/root/battery_capacity
      - /proc/uptime:/root/uptime
    restart: unless-stopped
    depends_on: 
      - mqtt
  couchdbsaver:
    image: iqtlabs/edgetech-couchdbsaver:latest
    build:
      context: ./edgetech-couchdb-saver/couchdbsaver
      dockerfile: ./Dockerfile
    environment:
      - TO_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - MQTT_IP=mqtt
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SERVER_IP_ADDR=${COUCHDB_SERVER_IP_ADDR}
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
      - couchdbserver
      - couchdbsetup
  couchdbserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SERVER_IP_ADDR=${COUCHDB_SERVER_IP_ADDR}
    volumes:
        - /home/mobian/dbdata:/opt/couchdb/data
  couchdbsetup:
    image: couchdb
    volumes:
      - ./edgetech-database-sync/couchdb/setup:/setup
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SERVER_IP_ADDR=${COUCHDB_SERVER_IP_ADDR}
      - PERIPHERAL=${PERIPHERAL}  
    restart: "no"
    command: sh -c "/setup/couchdbinit.sh"
    depends_on: 
        - couchdbserver
  # audio-recorder:
  #   image: iqtlabs/edgetech-audio-recorder:latest
  #   build:
  #     context: ../edgetech-audio-recorder/audiorecorder
  #     dockerfile: ./Dockerfile
  #   environment:
  #   devices:
  #     - "/dev/snd:/dev/serial1"
  #   restart: unless-stopped
  #   environment:
  #     - SEND_DATA_TOPIC=/AISonobuoy/<HOSTNAME>/Audio/edgetech-audio-recorder/string
  #     - SERIAL_PORT=/dev/serial1
  #     - C2_TOPIC=/AISonobuoy/<HOSTNAME>/C2/edgetech-c2/string
  #     - DATA_ROOT=/sensor-data
  #     - SENSOR_DIR=audio
  #     - FILE_PREFIX=hydrophone_audio_
  #     - MQTT_IP=mqtt
  #   volumes:
  #     - /home/mobian/sensor-data:/sensor-data