version: "3"
services:
  watchtower:
      image: containrrr/watchtower:latest
      network_mode: "host"
      environment:
        - WATCHTOWER_POLL_INTERVAL:3600
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --interval ${WATCHTOWER_POLL_INTERVAL:-3600}
  mqtt:
    image: iqtlabs/edgetech-mqtt:${SERVICES_IMAGE_TAG:-latest}
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./edgetech-core/mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  audio-recorder:
    image: iqtlabs/edgetech-audio-recorder:${SERVICES_IMAGE_TAG:-latest}
    build:
      context: ./edgetech-audio-recorder/audio-recorder
      dockerfile: ./Dockerfile
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  filesaver:
    image: iqtlabs/edgetech-filesaver:${SERVICES_IMAGE_TAG:-latest}
    build:
      context: ./edgetech-filesaver/filesaver
      dockerfile: ./Dockerfile
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  daisy:
    image: iqtlabs/edgetech-daisy:${SERVICES_IMAGE_TAG:-latest}
    devices:
      - "/dev/ttyACM0:/dev/serial0"
    build:
      context: ./edgetech-daisy/daisy
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  c2:
    image: iqtlabs/edgetech-c2:${SERVICES_IMAGE_TAG:-latest}
    build:
      context: ./edgetech-c2/c2
      dockerfile: ./Dockerfile
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  telemetry:
    image: iqtlabs/edgetech-telemetry:${SERVICES_IMAGE_TAG:-latest}
    build:
      context: ./edgetech-telemetry-pinephone/telemetry
      dockerfile: ./Dockerfile
    volumes:
      - /sys/class/power_supply/rk818-battery/capacity:/battery_capacity
      - /proc/uptime:/uptime
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  couchdb-server:
    image: couchdb:3.1.1
    restart: unless-stopped
    ports:
      - "5984:5984"
    volumes:
        - /home/mobian/couchdb-data:/opt/couchdb/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  couchdb-startup:
    image: iqtlabs/edgetech-couchdb-startup:${SERVICES_IMAGE_TAG:-latest}
    build:
      context: ./edgetech-couchdb-startup/couchdb-startup
      dockerfile: ./Dockerfile
    restart: "no"
    env_file:
      - .env
    depends_on:
      - couchdb-server
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  couchdb-saver:
    image: iqtlabs/edgetech-couchdb-saver:${SERVICES_IMAGE_TAG:-latest}
    build:
      context: ./edgetech-couchdb-saver/couchdb-saver
      dockerfile: ./Dockerfile
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  s3-uploader:
    image: iqtlabs/edgetech-s3-uploader:${SERVICES_IMAGE_TAG:-latest}
    build:
      context: ./edgetech-s3-uploader/s3-uploader
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    depends_on: 
      - mqtt
  http-uploader:
    image: iqtlabs/edgetech-http-uploader:${SERVICES_IMAGE_TAG:-latest}
    build:
      context: ./edgetech-http-uploader/http-uploader
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
