version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  audio-recorder:
    image: iqtlabs/edgetech-audio-recorder:latest
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - SEND_DATA_TOPIC=/AISonobuoy/<HOSTNAME>/Audio/edgetech-audio-recorder/string
      - C2_TOPIC=/AISonobuoy/<HOSTNAME>/C2/edgetech-c2/string
      - DATA_ROOT=/sensor-data
      - SENSOR_DIR=audio
      - FILE_PREFIX=hydrophone_audio_
      - MQTT_IP=mqtt
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
  filesaver:
    image: iqtlabs/edgetech-filesaver:latest
    environment:
      - SENSOR_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - TELEMETRY_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/telemetry/telemetry/string
      - C2_TOPIC=/AISonobuoy/<HOSTNAME>/C2/edgetech-c2/string
      - DATA_ROOT=/sensor-data
      - SENSOR_DIR=ais
      - TELEMETRY_DIR=telemetry
      - SENSOR_FILE_PREFIX=daisy_ais_
      - TELEMETRY_FILE_PREFIX=pinephone_telemetry_
      - MQTT_IP=mqtt
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
  daisy:
    image: iqtlabs/edgetech-daisy:latest
    devices:
      - "/dev/ttyACM0:/dev/serial0"
    environment:
      - SEND_DATA_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - SERIAL_PORT=/dev/serial0
      - MQTT_IP=mqtt
    restart: unless-stopped
    depends_on: 
      - mqtt
  c2:
    image: iqtlabs/edgetech-c2:latest
    environment:
      - C2_TOPIC=/AISonobuoy/<HOSTNAME>/C2/edgetech-c2/string
      - MQTT_IP=mqtt
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
  telemetry:
    image: iqtlabs/edgetech-telemetry:latest
    environment:
      - TELEMETRY_TOPIC=/AISonobuoy/<HOSTNAME>/telemetry/telemetry/string
      - BATTERY_CAPACITY_FILE_PATH=/battery_capacity
      - UPTIME_FILE_PATH=/uptime
      - MQTT_IP=mqtt
    volumes:
      - /sys/class/power_supply/rk818-battery/capacity:/battery_capacity
      - /proc/uptime:/uptime
    restart: unless-stopped
    depends_on: 
      - mqtt
  couchdbsaver:
    image: iqtlabs/edgetech-couchdbsaver:latest
    environment:
      - SENSOR_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - TELEMETRY_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/telemetry/telemetry/string
      - AUDIO_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/Audio/edgetech-audio-recorder/string
      - MQTT_IP=mqtt
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SERVER_IP_ADDR=${COUCHDB_SERVER_IP_ADDR}
      - DEVICE_IP=${DEVICE_IP}
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
      - couchdbserver
      - couchdbsetup
  couchdbserver:
    image: couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SERVER_IP_ADDR=${COUCHDB_SERVER_IP_ADDR}
    volumes:
        - /home/mobian/dbdata:/opt/couchdb/data
  couchdbsetup:
    image: couchdb
    volumes:
      - ../edgetech-database-sync/couchdb/setup:/setup
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SERVER_IP_ADDR=${COUCHDB_SERVER_IP_ADDR}
      - PERIPHERAL=${PERIPHERAL}  
    restart: "no"
    command: sh -c "/setup/couchdbinit.sh"
    depends_on: 
        - couchdbserver
  http-uploader:
    image: iqtlabs/edgetech-http-uploader:latest
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN}
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
  s3-uploader:
    image: iqtlabs/edgetech-s3-uploader:latest
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?error}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?error}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:?error}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:?error}
      - SEND_DATA_TOPIC=/AISonobuoy/<HOSTNAME>/edgetech-s3-uploader/string
      - C2_TOPIC=/AISonobuoy/<HOSTNAME>/C2/edgetech-c2/string
      - TARGET_DIR=/sensor-data
      - S3_BUCKET=aisonobuoy-test
      - MQTT_IP=mqtt
    env_file:
      - .env
    volumes:
      - /home/mobian/sensor-data:/sensor-data