version: "3"

networks:
    pinebuoy:
      driver: bridge
      driver_opts:
        com.docker.network.driver.mtu: 900

services:
  watchtower:
      networks:
        - pinebuoy
      image: containrrr/watchtower:latest
      environment:
        - WATCHTOWER_POLL_INTERVAL:3600
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --interval ${WATCHTOWER_POLL_INTERVAL:-3600}
  mqtt:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-mqtt:${SERVICES_IMAGE_TAG:-latest}
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  audio-recorder:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-audio-recorder:${SERVICES_IMAGE_TAG:-latest}
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  filesaver:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-filesaver:${SERVICES_IMAGE_TAG:-latest}
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  daisy:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-daisy:${SERVICES_IMAGE_TAG:-latest}
    devices:
      - "/dev/ttyACM0:/dev/serial0"
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  c2:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-c2:${SERVICES_IMAGE_TAG:-latest}
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  telemetry:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-telemetry:${SERVICES_IMAGE_TAG:-latest}
    volumes:
      - /sys/class/power_supply/rk818-battery/capacity:/battery_capacity
      - /proc/uptime:/uptime
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  couchdb-server:
    networks:
      - pinebuoy
    image: couchdb:3.1.1
    restart: unless-stopped
    ports:
      - "5984:5984"
    volumes:
        - /home/mobian/couchdb-data:/opt/couchdb/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  couchdb-startup:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-couchdb-startup:${SERVICES_IMAGE_TAG:-latest}
    restart: "no"
    env_file:
      - .env
    depends_on:
      - couchdb-server
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  couchdb-saver:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-couchdb-saver:${SERVICES_IMAGE_TAG:-latest}
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  s3-uploader:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-s3-uploader:${SERVICES_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    depends_on: 
      - mqtt
  http-uploader:
    networks:
      - pinebuoy
    image: iqtlabs/edgetech-http-uploader:${SERVICES_IMAGE_TAG:-latest}
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
